title = "ZoneManager"
gitRepoUrl = "https://github.com/re-sync-dev/ZoneManager" # From Git
gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "ignore"
onBrokenMarkdownLinks = "warn"

# From git:
url = "https://re-sync-dev.github.io"
projectName = "ZoneManager"
baseUrl = "/ZoneManager"
tagline = "Simple and straight forward zone management module"

[navbar]
title = "ZoneManager"

[home]
enabled = false
includeReadme = true

[footer]
style = "dark"
copyright = "Copyright © 2025 Re-Sync. Built with Moonwave and Docusaurus"